### ISSUE TITLE
Wiki αντί για Docs

### ISSUE THREAD

**Issue by vagelisp** [vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme#18]
Μήπως να κάναμε χρήση του wiki για να μην έχουμε τα docs μέσα στο theme ?

**Comment by o-samaras** [comment]
Ωραία ιδέα και πιστεύω πως θα είναι σίγουρα πιο δομημένη η πληροφορία. Μπορεί όμως κάποιος που δεν είναι μέλος του repo να γράψει στο wiki; Εάν όχι, θα το άφηνα ως έχει ώστε να μπορούν να συνεισφέρουν όλοι.

**Comment by vagelisp** [comment]
Μπορούμε να έχουμε τα docs και να τα βάζουμε στο wiki, δε ξέρω :/

**Comment by kosakk** [comment]
Όταν λέτε για docs αναφέρεστε σε αυτό; https://docs.github.com/en

**Comment by vagelisp** [comment]
@kosakk όχι, το φάκελο [docs](https://github.com/vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme/tree/main/docs) εννοούσα

https://github.com/vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme/tree/main/docs
