### ISSUE TITLE
Εισαγωγή Fonts για να είναι διαθέσιμα μέσα από τον Gutenberg

### ISSUE THREAD

**Issue by kosakk** [vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme#21]
Προτείνω μία ιδέα για συζήτηση: να δούμε πως μπορούμε να κάνουμε διαθέσιμα τα fonts που μας ενδιαφέρουν ούτως ώστε να είναι διαθέσιμα μέσα από τον Gutenberg.

**Comment by vagelisp** [comment]
Ναι θα μπουν fonts σίγουρα

**Comment by vagelisp** [comment]
https://www.meetup.com/wordpress_skg/events/291176080/
