### ISSUE TITLE
Το speakerdeck του 28ου meetup σταματάει κάπως απότομα

### ISSUE THREAD

**Issue by kosakk** [vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme#32]
Το speakerdeck του 28ου meetup με τις βασικές έννοιες του git σταματάει απότομα στο slide "Ας το δούμε στην πράξη" (#19) όπου δεν υπάρχει καθόλου περιεχόμενο εκτός από τον τίτλο. ([link](https://speakerdeck.com/wpgr/git-basikes-ennoies-kai-leitourgies?slide=19))

![image](https://user-images.githubusercontent.com/12464123/216772392-2e46595d-8fc4-486c-aea3-54ea927ccd0e.png)

**Comment by o-samaras** [comment]
Καλησπέρα @kosakk

Δεν είναι κάποιο θέμα της παρουσίασης. Εκεί τελειώνει η παρουσίαση και ξεκινάει το πρακτικό μέρος που υπάρχει στο video του workshop.
