### ISSUE TITLE
404 σε link του README.md

### ISSUE THREAD

**Issue by kosakk** [vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme#33]
Το link "[φάκελο docs](https://github.com/vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme/docs/)" (https://github.com/vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme/docs/) για τις περισσότερες πληροφορίες για το Git και το αρχείο theme.json στο README.md επιστρέφει 404. 

![image](https://user-images.githubusercontent.com/12464123/216772691-7bf479c4-3432-49a4-92f5-dd9ff29fb9c9.png)

Ομοίως και για την αγγλική έκδοση.

**Comment by vagelisp** [comment]
@o-samaras νομίζω εσυ τ ανέβασες ; Ρίξε μια μάτια όταν μπορέσεις

**Comment by vagelisp** [comment]
Άκυρο ( δε ξέρω και να διαβάζω ) @kosakk thanks θα το φτιάξουμε !
