### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by vagelisp** [vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme#5]
Θα χρειαστούμε κάτι για το readme.md και ίσως κι ενα contribute.md
Το readme καλο θα είναι πάνω απο το τεχνικό κομμάτι να έχει ενα κείμενο σχετικό με το "project"

**Comment by vagelisp** [comment]
@o-samaras ίσως το κείμενο που ετοιμάζεις ;

**Comment by o-samaras** [comment]
Οκ. Θα πρότεινα πέρα από το τι θα αφορά η σειρά των workshops (overview) να εμπλουτίζεται το readme.md με το τι πρόκειται να γίνει (ή τι έγινε) σε κάθε session, ώστε να λειτουργεί και ως ένα outline της γενικότερης δομής των workshops. Τι λες;
