### ISSUE TITLE
Theme Logo

### ISSUE THREAD

**Issue by vagelisp** [vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme#7]
Χρειαζόμαστε ένα λογότυπο για το theme, ίσως είναι καλή ιδέα να ζητήσουμε απο το community να βοηθήσει σ'αυτό.

Πως σας φαίνεται ?

**Comment by kosakk** [comment]
Το πρώτο πράγμα που μου έρχεται στο μυαλό όταν σκέφτομαι τη Θεσσαλονίκη είναι ο λευκός πύργος. Το SKG θεωρώ ότι είναι αρκετά πιασάρικο όνομα για theme από μόνο του. Less is more. Έκανα ένα outline του πρώτου και το πάντρεψα με το δεύτερο. Σίγουρα θέλει κι άλλη δουλειά. Το υποβάλλω σε .png για το preview. Υπάρχει και .xcf (GIMP file) για να είναι editable αν κάποιος θέλει να το βελτιώσει. Δε μπόρεσα να το ανεβάσω εδώ. 

![2017-10-09](https://user-images.githubusercontent.com/12464123/200383621-b25691c0-1353-44a4-939a-8f3b0034c498.png)

**Comment by fotisps** [comment]
Μία πρόταση σχετικά με το logo καθως δεν βλέπω να υπάρχει και κάποια ονοματοδοσία, γι αυτό βάζω σαν placeholder text το community theme makers ειναι η παρακάτω. Η ανω γραμματοσειρα που προτεινεται είναι η Fira Sans και η κατω, η play. Και οι 2 ειναι διαθεσιμες μεσω google fonts και για ελληνικούς χαρακτήρες. Προτιμώ να αποφευχθεί η χρήση σημαίας σε κάθε περίπτωση για σημειολογικούς λόγους.

![Logo-suggestion](https://user-images.githubusercontent.com/10010666/200495513-7cfd6f92-aa65-4f29-8a3b-d93f42e55b26.png)

**Comment by vagelisp** [comment]
Θα πρότεινα όμως ο Λευκός Πύργος να είναι λίγο πιο αφηρημένος ίσως. Το G1 είναι πολύ καλή βάση για συζήτηση νομίζω. Μήπως να κάναμε ένα thread εδω?  https://github.com/vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme/discussions

**Comment by christinamihou** [comment]
Για πιο αφαιρετικό λογότυπο συμφωνώ. πιστεύω ότι ίσως θα ήταν καλύτερα να καταλήξουμε πρώτα στο όνομα και μετά να σχεδιαστεί το λογότυπο.

**Comment by kosakk** [comment]
> [...]Προτιμώ να αποφευχθεί η χρήση σημαίας σε κάθε περίπτωση για σημειολογικούς λόγους.[...]

Νομίζω ότι έχεις δίκιο. Μάλλον ήταν κακή ιδέα.

**Comment by christinamihou** [comment]
Μια ακόμη πρόταση σχετικά με το όνομα του theme

Growth // Gr: Greece ,ο : one ή own (make it your own) , w : wordpress , th: theme και thessaloniki
Growth // ανάπτυξη, εξέλιξη // είναι θετική λέξη και μου ταίριαξε με το πνεύμα του group 

Επίσης για κάτι πιο μικρό θα μπορούσε να είναι και το Grow // μεγαλώνω, εξελίσσομαι ή Grown 

Αν καταλήξουμε σιγά σιγά στο όνομα, πιστεύω ότι θα βοηθήσει και στο σχεδιασμό του λογοτύπου
