### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by vagelisp** [vagelisp/Thessaloniki-WordPress-Meetup-Block-Theme#9]
Μήπως στήσουμε ένα container ?

**Comment by o-samaras** [comment]
Δεν είναι κακή ιδέα. Έχεις κάτι συγκεκριμένο στο μυαλό σου; Hard-core stuff (χύμα `docker-compose` κ.λπ.) που θα μπορούσαν να προσθέσουν και επιπλέον "εκπαιδευτικό" υλικό στο meetup, ή κάτι πιο εξευγενισμένο (π.χ. [vagrant](https://www.vagrantup.com/), [lando](https://lando.dev/), [ddev](https://ddev.readthedocs.io/)) που κρύβουν ένα μέρος από το χάος του docker;

**Comment by vagelisp** [comment]
Προς το hardcore θα έλεγα  αλλα θα μας επιτρέψει να έχουμε και content, plugins κλπ. 
Κάτι σαν αυτο που έχουμε και στο .org πχ δες το learn https://github.com/wordpress/Learn

Νομίζω θα ήταν πολύ χρήσιμο για όλους, βέβαια θα πρέπει να βάλουμε άλλο ενα εργαλείο στην εξίσωση αλλα νομίζω δε θα είναι πρόβλημα.
